### ISSUE TITLE
"NodeJS version requirement failed. Expected >= 16, got 15.5.0."

### ISSUE THREAD

**Issue by sylbru** [TerminalFi/LSP-copilot#101]
Hi!

So this is fixed in the end, but it’s unclear to me how it’s working. I had this error on install/on startup:

```
Failed to start LSP-Copilot […]

--- Error: ---
Node.js version requirement failed. Expected >= 16, got 15.5.0."
```

I tried specifying the path to node in my `LSP-copilot.sublime-settings`:

```json
{
    "command": [
        "/home/.../.nvm/versions/node/v18.1.0/bin/node", // instead of "${node_bin}"
        "${server_path}",
        "--stdio"
    ]
}
```
but it didn’t help. Then I noticed one other LSP server I was using (Intelephense) was probably running with NodeJS 15 since it was installed in NVM’s 15.5.0 folder. I upgraded the server by installing it with Node 18, and updated the path for that LSP plugin. Restarting Sublime Text, both LSP servers (Copilot and Intelephense) are starting without errors.

How does Sublime/LSP decide what version of Node to use? For Intelephense, I imagine it depends on what NVM is currently positioned on, but Copilot seems explicitly define the Node version to run (first part of the command in the settings), so why does it seem to be ignoring it?

**Comment by jfcherng** [comment]
Interesting. I think there is no sane way to define which Node for checking version. It's done in lsp_util lib.

**Comment by rchl** [comment]
It uses node present in the `PATH` so if you want to ensure that your system node is used, make sure that PATH is set correctly for ST. You can read more about such issues and way to solve them in https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers

Or just use the node instance provided by `LSP` (`lsp_utils`) which is the most robust way.

**Comment by rchl** [comment]
> LSP server I was using (Intelephense) was probably running with NodeJS 15 since it was installed in NVM’s 15.5.0 folder.

LSP never uses packages from your global nvm folders. It also installs them in a separate storage. So whatever you have installed globally doesn't really affect how it works.

**Comment by sylbru** [comment]
@rchl Ok, I understand but then I don’t know why installing a new version of the other language server (`npm install -g intelephense`) fixed the issue (and yes LSP-intelephense [does seem to ignore](https://github.com/sublimelsp/LSP-intelephense/blob/36b9fdf4a96b31a7535bc2532c56f1ef3abb55ad/plugin.py#L21) that globally installed one, as you explain). Must be some weird side effect. I see that I have `.nvm/versions/node/v15.5.0/bin` and `.nvm/versions/node/v18.1.0/bin` in my PATH, so maybe the order changed or something.

Now what I don’t get is, why does LSP-copilot settings include a path to the node binary, and doesn’t seem to take it into account?

I’ll try @jfcherng’s recommended lsp_utils settings for the future.

**Comment by jfcherng** [comment]
To conclude,

- LSP-* never do any version check. The logic is written in `lsp_utils` lib. LSP-* can specify the version limitation and `lsp_utils` will *ALWAYS* check limitation with the node executable from `which node`.
- If the version check failed, the server won't be started.
- If the version check passed, LSP-* just runs the command which is in its settings file.
