### ISSUE TITLE
No Copilot suggestions if same file is opened in a separate pane (i.e. Sublime "column")?

### ISSUE THREAD

**Issue by gregsadetsky** [TerminalFi/LSP-copilot#102]
See description and repro video below :-)

When the same file is opened in separate pane (I know that it feels weird -- but sometimes I forget that a file is a tab in one pane, and I open it again in a different pane), Copilot suggestions don't appear. It seems that suggestions only appear if the file is opened once.

https://user-images.githubusercontent.com/1017304/233140718-5cca3d99-3fc4-4372-b76a-a3ac2cb3a6ff.mov

**Comment by jfcherng** [comment]
We (me, and @TerminalFi) discussed this before in a private chat. We don't think this is solvable.

**Comment by gregsadetsky** [comment]
Super interesting! I wonder if a warning could be displayed..? That might be less confusing than not seeing Copilot (it took me a second to understand what was going on - since I had traced the issue before, I got it, but it could be confusing to someone who doesn't know?)

**Comment by TerminalFi** [comment]
It's something we are still considering. We might need to open a FR with Sublime.

**Comment by jfcherng** [comment]
Hmmm... seems get a working fix but I am not sure whether it causes other issues.

**Comment by rchl** [comment]
I haven't looked into the code of this package but I guess LSP must be handling such cases already? Maybe should get inspiration from there?

Not sure if relevant but LSP checks `view.is_primary()` in some places.

**Comment by jfcherng** [comment]
> I haven't looked into the code of this package but I guess LSP must be handling such cases already? Maybe should get inspiration from there?

Yeah. LSP seems working fine. Will check later.

**Comment by gregsadetsky** [comment]
Just confirmed, it works! Thank you so much for fixing this!!
