### ISSUE TITLE
No (documented) way to disable it for certain filetypes

### ISSUE THREAD

**Issue by malcolmocean** [TerminalFi/LSP-copilot#107]
I sometimes write prose or notes to self in sublime, and it's really annoying to get completion suggestions then. Can I turn it off for "Plain Text" files?

If not, that's a big issue for me (as it makes me turn it off altogether temporarily).

If yes, this should be documented in the settings and/or README somewhere. I did look.

**Comment by jfcherng** [comment]
as a quick answer: https://github.com/TerminalFi/LSP-copilot/blob/781b217d8de8cd32598d0e8f0be66a1773fe0850/LSP-copilot.sublime-settings#L22

**Comment by timfjord** [comment]
If you want to exclude a specific scope, you could [use `-`](https://www.sublimetext.com/docs/selectors.html#logical-not)
```
"selector": "source - text"
```

**Comment by jfcherng** [comment]
Depends on what "Plain Text" means, you may want to use

`(source | text | embedding) - text.plain`

**Comment by malcolmocean** [comment]
thanks guys! yeah as someone totally new to LSP, I had no idea where its bounds end and LSP-copilot's begin.
