### ISSUE TITLE
Not working: completions is always empty

### ISSUE THREAD

**Issue by Macmee** [TerminalFi/LSP-copilot#108]
I have everything set up and copilot status says im logged in. However I never get popups with suggestions. LSP logs show this:

```
:: [11:14:40.322] <-  LSP-copilot statusNotification: {'message': '', 'status': 'Normal'}
:: [11:14:40.322] <<< LSP-copilot (16) (duration: 596ms): {'completions': []}
```

any time I edit a file (.js files and .ts). It looks like everything is setup and "working" but I just never get any suggestions back and therefore no popups with suggestions.

**Comment by jfcherng** [comment]
What if you try the official Python exmaple?

```py
import datetime
def parse_expenses(expenses_string):
    """Parse the list of expenses and return the list of triples (date, value, currency).
    Ignore lines starting with #.
    Parse the date using datetime.
    Example expenses_string:
        2016-01-02 -34.01 USD
        2016-01-03 2.59 DKK
        2016-01-03 -2.72 EUR
    """
  	Manually trigger autocompletion here. 
```

**Comment by TerminalFi** [comment]
@Macmee 

Is there any update? If we don't hear back but the end of the week. We will close this issue as invalid and close.
