### ISSUE TITLE
Failed resolving Node.js Runtime

### ISSUE THREAD

**Issue by gemisigo** [TerminalFi/LSP-copilot#113]
I've tried to follow the simple installation guide and the problems started at step one. Installing LSP was done successfully, but after installing LSP-copilot I faced a warning stating that:

> Could not start LSP-copilot due to not being able to resolve suitable Node.js runtime on the PATH. Press the "Download Nodejs" button to get required Node.js version (note that it Will be used only by LSP and Will not affect your system otherwise).

Obviously, I chose "Download Node.js" which downloaded something and put it into "C:\Users\this_is_me\AppData\Local\Sublime Text\Package Storage\lsp_utils". Before I could restart Sublime Text, it popped an error dialog with this:

> Failed to start LSP-copilot - disabling for this window for the duration of the current session.
> Re-enable by running "LSP: Enable Language Server In Project" from the Command Palette.
> 
> --- Error: ---
> Failed resolving Node.js Runtime. Please check in the console for more details.

Trying the suggested "LSP: Enable Language Server In Project" will only resurrect the error dialog. I guess something with path is not set properly but I have no idea what. Any hints?

**Comment by jfcherng** [comment]
Did you restart ST?

**Comment by gemisigo** [comment]
Thanks for the quick reply. The OS is Win 11 Pro. I filed it here because it manifested after installing LSP-copilot (and it installing that lsp_util thing) and I guessed it failed to install it properly. But if you think I can post it there too.

**Comment by jfcherng** [comment]
Moved to https://github.com/sublimelsp/lsp_utils/issues/100
