### ISSUE TITLE
LSP-Copilot not working!

### ISSUE THREAD

**Issue by sindhujit1** [TerminalFi/LSP-copilot#120]
I get a popup in sublime text:

Failed to start LSP-copilot: - disabling for this window for the duration of the current session.
Re-enable by running "LSP:Enable Language Server in project" from the command palette.

I am not sure how to enable that, as I don't see any such options.

**Comment by TerminalFi** [comment]
Does the console or lsp log panel say anything.

**Comment by sindhujit1** [comment]
Nothing on the console. not sure where is the "lsp log panel".

**Comment by TerminalFi** [comment]
![CleanShot 2023-08-29 at 21 02 55@2x](https://github.com/TerminalFi/LSP-copilot/assets/32599364/2d9675b2-e586-4ff9-88b7-c20084c746b7)


Also you can try this


https://github.com/TerminalFi/LSP-copilot/assets/32599364/581e1a8d-3268-46f5-b337-d9006587405b

**Comment by sindhujit1** [comment]
How do you get that prompt? When I go to "Install Package" I see:

![image](https://github.com/TerminalFi/LSP-copilot/assets/60683901/7b077c11-54ad-4e50-ba27-024628300d73)

**Comment by jfcherng** [comment]
> How do you get that prompt? When I go to "Install Package" I see:

It's not "Install Package". Just type it in the command palette.

**Comment by sindhujit1** [comment]
The django project is running on my E1 server and I am connecting to it through SFTP. Could that somehow prompt this error ?

**Comment by jfcherng** [comment]
that looks like you dont have nodejs installed on your machine and at the same time you rejected to install with lso_utils.

**Comment by sindhujit1** [comment]
Yes LSP Co-pilot was installed using package control. I restarted sublime text. After that I tried downloading Node.js, but it fails with this popup:

![image](https://github.com/TerminalFi/LSP-copilot/assets/60683901/fa9095db-9a24-42a5-b0d3-fd58f4ce5a55)

**Comment by jfcherng** [comment]
> After that I tried downloading Node.js,

how did you do this?

**Comment by TerminalFi** [comment]
@sindhujit1 any update ? Else can we close

**Comment by sindhujit1** [comment]
I have installed Nodejs on my local machine as well on the E1 machine where our sublimeText connects to and where our code resides. However I still get a failed message.

**Comment by sindhujit1** [comment]
We are behind a proxy and so I think there is some issue with that. Here's the error:

![image](https://github.com/TerminalFi/LSP-copilot/assets/60683901/28378434-ff44-4055-8d79-e12287a75078)

**Comment by jfcherng** [comment]
Maybe set a proxy server for NPM. https://www.jhipster.tech/configuring-a-corporate-proxy/

**Comment by TerminalFi** [comment]
Closing as inactive.
