### ISSUE TITLE
How can I start the Copilot LSP server?

### ISSUE THREAD

**Issue by wongjiahau** [TerminalFi/LSP-copilot#121]
Is it possible to start the Copilot LSP server without using the Sublime editor? I wish to use the server for other editor that is LSP-compatible

**Comment by jfcherng** [comment]
I guess you should ask in the editor's community then.

**Comment by wongjiahau** [comment]
It’s actually for my own editor where I built myself, and there’s only one user at the moment 😅

**Comment by TerminalFi** [comment]
Not easily. But you don't want LSP-copilot. You need likely the copilot-node-server.
