### ISSUE TITLE
Suggestion: key for closing the suggestions panel

### ISSUE THREAD

**Issue by viraptor** [TerminalFi/LSP-copilot#129]
If I request more completions and get a panel of them, it seems there's no easy way to dismiss it apart from the "close" button at the top.
I'd like to be able to `<esc>` out of it / close it.

**Comment by TerminalFi** [comment]
You can already do this by adding your own key binding for the command `copilot_close_panel_completion`

**Comment by Mr-HaleYa** [comment]
![image](https://github.com/TerminalFi/LSP-copilot/assets/42821995/8a68f0e4-3b12-4953-8a1c-ead15b988207)
Go to keybinds and add 
```
	{
		"keys": ["ctrl+shift+`"],  // <----SET YOUR KEYBIND HERE
		"command": "copilot_close_panel_completion"
	},
```

**Comment by viraptor** [comment]
I'm trying something that should probably work, but doesn't:
```
    { "keys": ["escape"], "command": "copilot_close_panel_completion", "context":
        [
            { "key": "is_visible_panel_completions", "operator": "equal", "operand": true }
        ]
    }
```
Based on the [commit referenced](https://github.com/TerminalFi/LSP-copilot/pull/89/files#diff-fcbd8946ecbd83f9e57ccc4929d2ea9d7c666edac97754f4c24309252a06422cR30) in the issue you mentioned. Any idea what's going wrong here?

**Comment by TerminalFi** [comment]
Key is `setting.copilot.completion.is_visible_panel_completion`

**Comment by viraptor** [comment]
Tried:
```
    { "keys": ["escape"], "command": "copilot_close_panel_completion", "context":
        [
            { "key": "setting.copilot.completion.is_visible_panel_completion", "operator": "equal", "operand": true }
        ]
    }
```
and it <esc> doesn't work with the panel open.

**Comment by TerminalFi** [comment]
@viraptor I've identified the issue and I am working on it

**Comment by TerminalFi** [comment]
Just to give you an update HTMLSheets don't have a settings object and therefore we can't actually check or set a setting value. 

So this is what fails to provide a way to do context keybindings. There is an open issue on Sublime text for a similar issue. Which would also fix this. https://github.com/sublimehq/sublime_text/issues/3826
