### ISSUE TITLE
Question: is there any keybindings for choosing the next suggestion?

### ISSUE THREAD

**Issue by davidhcefx** [TerminalFi/LSP-copilot#131]
Is there any bindable commands so that I can iterate over all provided suggestions, instead of clicking in the popup window? Thanks!

**Comment by jfcherng** [comment]
It's a good practise to read plugin's default keybinding, settings.
https://github.com/TerminalFi/LSP-copilot/blob/519139949c05381829442b2631779065e22cd970/Default.sublime-keymap#L24-L45

**Comment by davidhcefx** [comment]
Oh I thought everything I needed to know was in the README, thanks for your suggestion!
