### ISSUE TITLE
Error: "Failed resolving Node.js Runtime. Please see Sublime Text console for more information."

### ISSUE THREAD

**Issue by edpichler** [TerminalFi/LSP-copilot#133]
First time using SublimeTexst with LSP. 
I followed all the instructions but I can´t make it work. I have node and nvm installed.

![image](https://github.com/TerminalFi/LSP-copilot/assets/358696/1c29df6a-b3f4-4475-9a98-b761041110dc)

![image](https://github.com/TerminalFi/LSP-copilot/assets/358696/cd797fb9-51bd-42ae-8b56-449fa75c5fbb)

![image](https://github.com/TerminalFi/LSP-copilot/assets/358696/c53dd38b-8ed9-412d-8b6c-b4fceefc4e1e)

```
---------------------------
Sublime Text
---------------------------
Failed to start LSP-copilot - disabling for this window for the duration of the current session.
Re-enable by running "LSP: Enable Language Server In Project" from the Command Palette.

--- Error: ---
Failed resolving Node.js Runtime. Please see Sublime Text console for more information.
---------------------------
OK   
---------------------------
```

**Comment by jfcherng** [comment]
I would assume `nvm` provides a magic script for shell to include and non-shell env just doesn't care that. My best issue is just let LSP manages its own local Node.js installation which is guarantee working. If you must use your own Node.js installation via NVM, make it available in your PATH env.

**Comment by rchl** [comment]
The actual issue should be mentioned earlier in sublime text console

**Comment by edpichler** [comment]
I am having a hard time understanding the 'Troubleshooting instructions' and the error messages in LSP. 

- In this context is "LSP-copilot" a language server?

I am trying to configure the 'paths' for node and I will keep this thread updated.

**Comment by edpichler** [comment]
> The actual issue should be mentioned earlier in sublime text console

It´s the whole log in the picture.

**Comment by edpichler** [comment]
Is anything missing here? 
![image](https://github.com/TerminalFi/LSP-copilot/assets/358696/0f83fe97-7290-4622-903c-18161f29898b)

**Comment by edpichler** [comment]
> I would assume `nvm` provides a magic script for shell to include and non-shell env just doesn't care that. My best suggestion is just let LSP (`lsp_utils` actually) manages its own local Node.js installation which is guaranteed working. If you must use your own Node.js installation, make it available via PATH env.
> 
> https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers
> 
> This issue doesn't really related to this repository. You will face it with any Node-based LSP-* plugin.

My only installation is the one by NVM. 
It creates a `NVM_HOME `env. So I tried to create the missing ones manually but I am getting the same error.

**Comment by edpichler** [comment]
I was checking the source code and now I suspect it is expecting not the node path but the npm path.
I don´t have experience with node eco-system..

![image](https://github.com/TerminalFi/LSP-copilot/assets/358696/8079d635-ec0b-481c-b5a9-3e9f3e6fef27)

**Comment by rchl** [comment]
> > The actual issue should be mentioned earlier in sublime text console
> 
> It´s the whole log in the picture.

I don't think so.

But you should be able to fix by adding this to `~/.zprofile`:

```sh
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
```

**And remove override for the `command` setting.**

**Comment by rchl** [comment]
Oh, wait. You are on Windows...

Then I'm not sure.

Would recommend switching to bundled Node by setting:

```
"nodejs_runtime": ["local"],
```

in `Preferences: LSP Utils Settings`.

**Comment by edpichler** [comment]
Thanks for your help guys. I could make it work with other LSP servers. I tried everything here. I have to give it up.

![image](https://github.com/TerminalFi/LSP-copilot/assets/358696/5ac0a6d6-d7fe-4aa0-82b1-8935ec8a662e)

**Comment by rchl** [comment]
You are not following the instructions. I said you have to set it in `Preferences: LSP Utils Settings` (which is in Command Palette).

**Comment by edpichler** [comment]
> You are not following the instructions. I said you have to set it in `Preferences: LSP Utils Settings` (which is in Command Palette).

I did it and the problem persists. 
![image](https://github.com/TerminalFi/LSP-copilot/assets/358696/8114bf6b-7779-44a2-a8ef-0915cc817967)

**Comment by udoga** [comment]
I had the same problem. I solved it by downloading Node.js without NVM and making sure that both "node" and "npm" binaries are accessible from my PATH (the LSP plugin looks for both). This way no additional configuration is needed in Sublime Text.

**Comment by brian6932** [comment]
> solved it by downloading Node.js without NVM and making sure that both "node" and "npm" binaries are accessible from my PATH

Specifically the `npm` part of this needs to be removed. You can `corepack disable npm` and now Sublime's LSP's crying for no reason.
