### ISSUE TITLE
How often does copilot.vim get updated?

### ISSUE THREAD

**Issue by beautifulcoder** [TerminalFi/LSP-copilot#135]
Mostly have a general question, I am noticing the repo has not been updated since 2022. The `copilot-node-server` package it uses is two months old. How often do updates occur in the plugin?

**Comment by TerminalFi** [comment]
Copilot.vim just had a new release 2 days ago. Are you talking about our repository ?

copilot-node-server generally receives an update within a few days of copilot.vim

**Comment by TerminalFi** [comment]
Our repository is using tags, so we don’t need to actually push a new release in order for users to get an update. 

https://github.com/TerminalFi/LSP-copilot/tags

Our last tag was in Jan, we are obviously due for a update :)

**Comment by jfcherng** [comment]
I maintained copilot-node-server. But I am a little lazy to update it here since it requires another person to approve it and more importantly, I don't know what it updates.

**Comment by TerminalFi** [comment]
@jfcherng we can remove approval need. Now that it's stable.

**Comment by jfcherng** [comment]
v1.24.0 doesn't seem to work in my local test.

**Comment by jfcherng** [comment]
Hmm... `bin/copilot-node-server` doesn't work while `copilot/dist/agent.js` works.

**Comment by jfcherng** [comment]
Updated to v1.24.0.

**Comment by beautifulcoder** [comment]
Thank you all, I noticed my local plugin automatically updated to the latest and everything still works correctly.
