### ISSUE TITLE
Completing when I press tab, even though hook_to_auto_complete_command is false

### ISSUE THREAD

**Issue by TehShrike** [TerminalFi/LSP-copilot#138]
After restarting yesterday and presumably having my ST packages updated, LSP-copilot has been auto-inserting suggested text when I press tab (my auto_complete trigger).

I am using the default `"hook_to_auto_complete_command": false,` settings.

**Comment by jfcherng** [comment]
We have no recent change related to that but honestly I don't like this plugin to use Tab key because it's UI can appear aside with ST autocompletion, making press Tab a unpredictible behavior or there is no way to decide use copilot or ST completion.

**Comment by TehShrike** [comment]
Yeah I already have a separate keyboard shortcut set up for "apply change", I really don't want this plugin to be inserting anything when I hit tab.  Any ideas on how I can disable this behavior?
