### ISSUE TITLE
TAB key still accepts completion when other key is chosen in config.

### ISSUE THREAD

**Issue by ardabro** [TerminalFi/LSP-copilot#142]
I redefined the accept_completion key to backslash and it works, but sadly it still accepts with TAB.

    {
        "keys": [
            "\\"                  
        ],
        "command": "copilot_accept_completion",
        "context": [
            {
                "key": "copilot.is_on_completion"
            }
        ]
    },

**Comment by TerminalFi** [comment]
I've just merged https://github.com/TerminalFi/LSP-copilot/pull/140


It'll take a bit to propagate to package control. Should solve this

**Comment by jfcherng** [comment]
Now you can set `commit_completion_on_tab` to `false` in LSP-copilot's plugin settings to disable the completion using "Tab".
