### ISSUE TITLE
In "panel completion", `Mean Probability` seems to be always `0`

### ISSUE THREAD

**Issue by jfcherng** [TerminalFi/LSP-copilot#154]
Originally asked in https://discord.com/channels/280102180189634562/645268178397560865/1241115323550142536.

That is, https://github.com/TerminalFi/LSP-copilot/blob/90b9176a7c22feb3dec75465c606aa4022cd1194/plugin/ui/panel_completion.py#L264C17-L264C21
![image](https://github.com/TerminalFi/LSP-copilot/assets/6594915/0b86d629-596b-4cf8-9ca7-759f1638f55f)

The code is good but in the server payload it just says `0`s. So I guess that `Mean Probability` only provides confusion now? But at the same time, we don't know those `0`s are intentional or what.

Let's remove them from headers?

**Comment by timfjord** [comment]
If it is always `0`, hiding it makes sense.
But has it been always like that? Maybe we are missing something in how we call the API

**Comment by jfcherng** [comment]
> If it is always `0`, hiding it makes sense.
> But has it been always like that? Maybe we are missing something in how we call the API

pretty sure it has other value back to shen we implemented it.

**Comment by timfjord** [comment]
Hmm, then they probably changed something along the way.

**Comment by TerminalFi** [comment]
Fixed / Removed in #167
