### ISSUE TITLE
Can't sign out

### ISSUE THREAD

**Issue by tomerarnon** [TerminalFi/LSP-copilot#156]
My LSP-copilot is accidentally signed into a github account which does not have copilot access. Hence, it doesn't work. When I try to sign out to use the correct credentials, `Copilot: Sign Out` has no effect...

**Comment by jfcherng** [comment]
Interesting... I can reproduce this with a account which doesn't subscribe to copilot.

**Comment by jfcherng** [comment]
> As a workaround, you can delete its session by deleting the whole `github-copilot` folder.

If eventually the GitHub officials don't really care Sublime Text, we probably have to delete those directory directly rather than calling `Copilot.vim`'s `signOut` command.

**Comment by jfcherng** [comment]
It looks like I can't sign out a subscribed account either.

```
:: [14:44:16.071] --> LSP-copilot signOut (32): {}
:: [14:44:16.085] <-  LSP-copilot featureFlagsNotification: {'rt': True, 'sn': False, 'chat': True}
:: [14:44:16.085] <<< LSP-copilot (32) (duration: 14ms): {'status': 'OK', 'user': 'jfcherng'}
```

**Comment by jfcherng** [comment]
A fixed new release has been tagged and will be available on Package Control within hours.

**Comment by jfcherng** [comment]
This is claimed to be fixed in https://github.com/orgs/community/discussions/126315#discussioncomment-9691739 anyway.
