### ISSUE TITLE
Visual feedback that LSP-copilot is busy

### ISSUE THREAD

**Issue by KimLindblom** [TerminalFi/LSP-copilot#166]
I have LSP-copilot triggering copilot_ask_completions manually on a keypress, with the phantom completion_style. Very often it simply does not give me a suggestion, I assume this is because it simply does not have a good suggestion to give in that context.

However, there is no way for me to tell that it has given up, or if it's still waiting for the copilot auto completion process to finish. It would be nice if there was a setting for making the status bar show something to indicate that LSP-copilot is currently fetching. Even better would be if the phantom itself could say "loading..." or something to that effect.

I get that this might be annoying for those who have LSP-copilot always on with it's suggestions, but for those of us who trigger it manually have some sort of visual feedback that my keypress did anything at all would be good.

**Comment by jfcherng** [comment]
A text hint in the status bar may be less effort to implement and less intrusive.

**Comment by timfjord** [comment]
Yeah, I agree. Having something in the status would definitely be better than updating it with the phantom, especially given the issues with the jumping cursor.

But in general, most of the time the feedback is instant. 
If there is no completion in, I don't know, 1 sec, then 99% it just doesn't have what to suggest

**Comment by TerminalFi** [comment]
Maybe something similar to package controls animated icon. 

Lsp-copilot (rotating)

**Comment by jfcherng** [comment]
Implemented in https://github.com/TerminalFi/LSP-copilot/pull/174

**Comment by jfcherng** [comment]
Released in `v0.2.15`. Should be available within hours.
