### ISSUE TITLE
Follow up link rendering / command issue

### ISSUE THREAD

**Issue by TerminalFi** [TerminalFi/LSP-copilot#182]
Sometimes copilot returns a link with ` in it. This breaks the link. 

Need to investigate

**Comment by TerminalFi** [comment]
![TerminalFi 2024-07-12 at 21 21 03@2x](https://github.com/user-attachments/assets/713b4c93-c9da-4fe3-ab64-fdb4c7930280)


Looks like we need to insert follow up after mdpopup renders?

**Comment by jfcherng** [comment]
Could the issue be that the quote in following up is not escaped?

**Comment by TerminalFi** [comment]
mdpopups see it and converts it to code. Maybe escaping fixes that

**Comment by jfcherng** [comment]
Do you know any question that would likely reproduce this issue?

**Comment by TerminalFi** [comment]
> Do you know any question that would likely reproduce this issue?

You can modify the follow up by modifying windows settings for testing and debugging :)

**Comment by jfcherng** [comment]
nah, I don't even know what the server payload is.

**Comment by jfcherng** [comment]
https://github.com/TerminalFi/LSP-copilot/pull/188
