### ISSUE TITLE
spinner / other loading indicator

### ISSUE THREAD

**Issue by mustafa0x** [TerminalFi/LSP-copilot#183]
often i'm not sure if copilot is loading or stuck (ie needs restarting). a spinner (or even three flashing dots) in the tool bar would be nice. thanks!

**Comment by TerminalFi** [comment]
This is already launched and in place. When you type, you should see the LSP-copilot () change 

Are you not seeing this

**Comment by mustafa0x** [comment]
ah, i didn't notice, i saw it now, thanks a ton!
