### ISSUE TITLE
byok / anthropic claude

### ISSUE THREAD

**Issue by mustafa0x** [TerminalFi/LSP-copilot#184]
Hi, thanks for this plugin!

Is it possible we use this plugin with other ai providers, or with gpt4, but byok (bring your own key)? I noticed cursor.com has a byok feature.

Thanks again!

**Comment by TerminalFi** [comment]
This is based solely on Microsoft Copilot. If you have a service that replicates Copilots API calls, this could be achieved via the proxy URL.

**Comment by mustafa0x** [comment]
https://x.com/GergelyOrosz/status/1811712155198120303

<img width="679" alt="image" src="https://github.com/user-attachments/assets/118b0001-8eee-4c8a-805a-418f0bba2e02">

**Comment by jfcherng** [comment]
You may want to check https://packagecontrol.io/packages/OpenAI%20completion

**Comment by mustafa0x** [comment]
Appreciated folks, thanks! I'll check that plugin out.
