### ISSUE TITLE
Copilot chat

### ISSUE THREAD

**Issue by Mr-HaleYa** [TerminalFi/LSP-copilot#185]
Dumb question but how do I open the copilot chat windows?.... #99 It's not explained anywhere as far as I can tell and I've never used it or seen it in use... 

It's shown as an example in the readme but that's the only context I could find
![image](https://github.com/user-attachments/assets/8400fbe0-0d01-4b01-97a1-fbf97faf3ec7)

**Comment by TerminalFi** [comment]
If you are on the latest version you can open command palette and then type Chat and it should show up

**Comment by Mr-HaleYa** [comment]
Thank you. Should this be in the readme?

For me it is `Ctrl+Shift+P` then type chat and select `Copilot: Chat`

**Comment by TerminalFi** [comment]
@Mr-HaleYa Feel free to make a PR

**Comment by TerminalFi** [comment]
@Mr-HaleYa like you would set any other Sublime keybinding. If you need help, I can write and example Monday

**Comment by Mr-HaleYa** [comment]
That would be great, I have very little experience with sublime keybinding.

**Comment by TerminalFi** [comment]
Here is a video showing how to do this. I did it on a Mac, but should be the same any platform


https://github.com/user-attachments/assets/86f2ff4e-31bc-4534-8ff7-9e2be14caa09

**Comment by chrissv** [comment]
> @Mr-HaleYa like you would set any other Sublime keybinding. If you need help, I can write and example Monday

Of you could ask Copilot to write it for you 😃
