### ISSUE TITLE
How to change the color of the follow up link?

### ISSUE THREAD

**Issue by sunnyAfterSnow** [TerminalFi/LSP-copilot#189]
![image](https://github.com/user-attachments/assets/c9175cfe-fa8f-45b4-9f91-a8dc9bd2be44)

I'm using the  [monokai pro](https://monokai.pro/) color scheme and theme. I opened copilot chat and asked a question, but the link is not clear in the generated answer?

**Comment by jfcherng** [comment]
I doubt that is just the default color of a `<a>` tag for your color scheme. I don't see we define a color for it (and we shouldn't, since it should be based on user's color scheme).

**Comment by jfcherng** [comment]
You can run `Copilot: Edit CSS: Chat Panel` and add following CSS

```css
.icon-link {
  color: green;
}
```

but that applies to all `.icon-link` class since we don't make the "follow up" special.

**Comment by jfcherng** [comment]
Okay so I think it just use the `--bluish` color from your color scheme.
https://github.com/facelessuser/sublime-markdown-popups/blob/e8fb5ceb9667a552c6cf3fb7e668c00df83e1d57/st3/mdpopups/css/default.css#L4

If `--bluish` is not defined in your color scheme, ST will deduce one, which is usually not optimal.

**Comment by sunnyAfterSnow** [comment]
> You can run `Copilot: Edit CSS: Chat Panel` and add following CSS
> 
> ```css
> .icon-link {
>   color: green;
> }
> ```
> 
> but that applies to all `.icon-link` class since we don't make the "follow up" special.
> 
> Or ideally find a way to set the default color of the `<a>` tag of your color scheme. Maybe this is related to mdpopup's CSS as well I am not sure...

![image](https://github.com/user-attachments/assets/ad07d323-619d-4c85-be16-df149120751a)
**Thank you for your answer!**
