### ISSUE TITLE
Error: "The LSP-copilot server has crashed 5 times in the last 180 seconds. You can try to Restart it or you can choose Cancel to disable it for this window for the duration of the current session. Re-enable by running "LSP: Enable Language Server In Project" from the Command Palette."

### ISSUE THREAD

**Issue by xaezarrio** [TerminalFi/LSP-copilot#205]
got this error when open sublime

![image](https://github.com/user-attachments/assets/a176ec11-3ca6-48c0-bfd9-25154a780e65)

try restart but still show this message

**Comment by jfcherng** [comment]
Can you run LSP trouble shooting from the command palette for LSP-copilot?

**Comment by xaezarrio** [comment]
It says require node 18.x, i tried to change my nodejs then it works!

thanks
