### ISSUE TITLE
Cannot run LSP-copilot.

### ISSUE THREAD

**Issue by pioz** [TerminalFi/LSP-copilot#210]
I'm not able to run Copilot with my Sublime Text editor.

I've done this steps:
- Install the package LSP from command palette (install package)
- Install the package LSP-copilot from command palette (install package)
- Just after the installation I see this popup error:
<img width="314" alt="Screenshot 2024-09-27 at 10 44 20" src="https://github.com/user-attachments/assets/5151f579-60cf-482a-a17f-b19c3548b72a">

- I've restart sublime
- Just after restart I see this popup error:
<img width="278" alt="Screenshot 2024-09-27 at 10 44 31" src="https://github.com/user-attachments/assets/5daad1b8-33d4-4040-b835-077a4f072458">

I'm on mac os x 14.6.1 and Sublime Text 4180. My node is installed:
```
node --version                 
v20.17.0
```
```
which node       
/Users/pioz/.local/share/mise/installs/node/lts/bin/node
```

Now if I open the command palette and type "Copilot: Sign In" I do not see any available option:
<img width="823" alt="Screenshot 2024-09-27 at 10 48 46" src="https://github.com/user-attachments/assets/c84c7a1e-750f-46be-beaf-1fdc632d8893">

My Troubleshooting: LSP-copilot output is:
```
# Troubleshooting: LSP-copilot
## Version
 - LSP: 2.2.0
 - Sublime Text: 4180
## Server Test Run
 - exit code: -1
 - output
```
Failed resolving Node.js Runtime. Please check in the console for more details.
```
## Server Configuration
 - command
```json
[
  "${node_bin}",
  "${server_path}",
  "--stdio"
]
```
 - shell command
```sh

```
 - selector
```
source | text | embedding
```
 - priority_selector
```
source | text | embedding
```
 - init_options
```json
{}
```
 - settings
```json
{
  "auto_ask_completions": true,
  "commit_completion_on_tab": true,
  "completion_style": "popup",
  "debug": false,
  "hook_to_auto_complete_command": false,
  "local_checks": false,
  "prompts": [
    {
      "description": "Review code and provide feedback.",
      "id": "review",
      "prompt": [
        "Review the referenced code and provide feedback.",
        "Feedback should first reply back with the line or lines of code, followed by the feedback about the code.",
        "Do not invent new problems.",
        "The feedback should be constructive and aim to improve the code quality.",
        "If there are no issues detected, reply that the code looks good and no changes are necessary.",
        "Group related feedback into a single comment if possible.",
        "Present each comment with a brief description of the issue and a suggestion for improvement.",
        "Use the format `Comment #: [description] [suggestion]` for each comment, # representing the number of comments.",
        "At last provide a summary of the overall code quality and any general suggestions for improvement."
      ]
    }
  ],
  "proxy": "",
  "status_text": "{% if is_copilot_ignored %}{{ is_copilot_ignored }}{% elif is_waiting %}{{ is_waiting }}{% elif server_version %}v{{ server_version }}{% endif %}",
  "telemetry": false
}
```
 - env
```json
{}
```

## Active view
 - File name
```
None
```
 - Settings
```json
{
  "auto_complete_selector": null,
  "lsp_active": null,
  "syntax": null
}
```

## Project / Workspace
 - folders
```json
[
  "/Users/pioz/Code/cardtrader"
]
```
 - is project: False

## LSP configuration

```json
{
  "clients": {
    "copilot": {
      "command": [
        "node",
        "/path/to/copilot-lsp",
        "--stdio"
      ],
      "enabled": true,
      "env": {
        "PATH": "/usr/local/bin:/path/to/node:/path/to/copilot-lsp:$PATH"
      }
    }
  }
}
```
## System PATH
 - /usr/local/bin
 - /System/Cryptexes/App/usr/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
 - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
 - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
 - /opt/X11/bin
 - /usr/local/MacGPG2/bin
 - /Library/TeX/texbin
 - /Applications/Wireshark.app/Contents/MacOS
 - /Applications/VMware Fusion.app/Contents/Public
 - /usr/local/go/bin
```
```

My console output:
```
--- lsp_utils Node.js resolving start ---
Resolving Node.js Runtime in env PATH for package LSP-copilot...
 * Failed: "node" binary not found
Resolving Node.js Runtime from lsp_utils for package LSP-copilot...
 * Binaries check failed: "node" binary not found
 * Download skipped
--- lsp_utils Node.js resolving end ---
no command for selector: noop:
Unable to start subprocess for LSP-copilot
Traceback (most recent call last):
  File "/Users/pioz/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 257, in start_async
    if plugin_class.needs_update_or_installation():
  File "/Users/pioz/Library/Application Support/Sublime Text/Lib/python38/lsp_utils/_client_handler/abstract_plugin.py", line 101, in needs_update_or_installation
    server = cls.get_server()
  File "/Users/pioz/Library/Application Support/Sublime Text/Lib/python38/lsp_utils/npm_client_handler.py", line 122, in get_server
    cls.__server = ServerNpmResource.create({
  File "/Users/pioz/Library/Application Support/Sublime Text/Lib/python38/lsp_utils/server_npm_resource.py", line 49, in create
    raise Exception('Failed resolving Node.js Runtime. Please see Sublime Text console for more information.')
Exception: Failed resolving Node.js Runtime. Please see Sublime Text console for more information.
```

Can you help me to install Copilot on my Sublime Editor?

**Comment by jfcherng** [comment]
I believe this is a duple of https://github.com/TerminalFi/LSP-copilot/issues/133

**Comment by pioz** [comment]
I've modify my `LSP.sublime-settings` with this:
```
{
  "clients": {
    "copilot": {
      "enabled": true,
      "command": [
        "/Users/pioz/.local/share/mise/installs/node/lts/bin/node",
        "${server_path}",
        "--stdio"
      ],
      "env": {
        "PATH": "/Users/pioz/.local/share/mise/installs/node/lts/bin:$PATH"
      }
    }
  }
}
```

But I still have the same problem. Please help!

**Comment by pioz** [comment]
Ok, adding in `lsp_utils.sublime-settings`, "nodejs_runtime": ["local"]` the Troubleshooting exit with code 0 🤟🏻

But now if I open the command palette and type "Copilot: Sign In" I do not see any available option.

**Comment by jfcherng** [comment]
I believe somewhere should emit an error, such as ST console.

**Comment by jfcherng** [comment]
Well, that's why I would suggest people to use Node.js managed by lsp_utils. Otherwise, everyone has their own environment and that makes debug annoying.
