### ISSUE TITLE
Sometimes copilot chat generates infinitely

### ISSUE THREAD

**Issue by dragos240** [TerminalFi/LSP-copilot#212]
When I have a code slice like the following:
```py
        if item is not None:
            layout.label(text=item["name"], icon="FILE")
```

and I ask it "Other common options for the icon parameter", it will start repeating itself and there's no way to stop. See image:

![image](https://github.com/user-attachments/assets/845667ce-dc92-4b36-ad04-c5ed23763312)

I'm unsure if this is a problem with copilot itself or the LSP plugin

**Comment by TerminalFi** [comment]
@dragos240 I am unable to replicate. If you see this and can provide LSP Logs, that would be most helpful
