### ISSUE TITLE
Model switcher

### ISSUE THREAD

**Issue by mustafa0x** [TerminalFi/LSP-copilot#214]
https://github.blog/news-insights/product-news/bringing-developer-choice-to-copilot/

Is this possible with lsp-copilot?

**Comment by jfcherng** [comment]
Typically should be asked in https://github.com/github/copilot.vim, which is the server we use. But fwiw, they don't want you to ask there, so just go GitHub Copilot's discussion as its readme suggests.

**Comment by jfcherng** [comment]
Closed as we are only focus on what [github/copilot.vim](https://github.com/github/copilot.vim?rgh-link-date=2024-10-29T17%3A45%3A00Z) provides.

**Comment by plutonium-239** [comment]
They've added a model switcher: https://github.com/github/copilot.vim/issues/77#issuecomment-3697899145

Can this also be added as a switcher in this plugin? Just a command will suffice (it would be great to also display it in the chat panel or status bar)
