### ISSUE TITLE
Selecting text in copilot chat

### ISSUE THREAD

**Issue by ringlej** [TerminalFi/LSP-copilot#215]
Sometimes I want to be able to select text from a copilot chat in sublime text so I can copy it to the clipboard, but selecting text is disabled. You can only put copy to the clipboard code snippets that are provided by copilot.

Is there a way to enable this?

**Comment by jfcherng** [comment]
It's not disabled. It's unsupported. https://github.com/sublimehq/sublime_text/issues/3471
