### ISSUE TITLE
No sign in popup on WSL

### ISSUE THREAD

**Issue by mcrampon** [TerminalFi/LSP-copilot#216]
Hi!

I'm running Sublime from inside a WSL instance. In this case, it seems that the Github popup used to sign in never appears.

Any workaround I could use? Like manually setting a token somewhere in a config file?

**Comment by jfcherng** [comment]
> Like manually setting a token somewhere in a config file?

https://github.com/TerminalFi/LSP-copilot/issues/156#issuecomment-2136442438 if you have that file on other signed machine or VSCode.

**Comment by jfcherng** [comment]
The GitHub pop is opened with ST's plugin API in https://github.com/TerminalFi/LSP-copilot/blob/20f7cbc275dc6e008c0363942acefc662b4940f0/plugin/commands.py#L780-L781 . So that sounds like a bug in ST core or non-goal on WSL.

**Comment by mcrampon** [comment]
> The GitHub pop is opened with ST's plugin API in
> 
> https://github.com/TerminalFi/LSP-copilot/blob/20f7cbc275dc6e008c0363942acefc662b4940f0/plugin/commands.py#L780-L781
> . So that sounds like a bug in ST core or non-goal on WSL.
> 
> As a workaround, maybe we can print the verification URL and usercode to ST console so that the user can manually open it.

That would be nice indeed 👍 

> > Like manually setting a token somewhere in a config file?
> 
> [#156 (comment)](https://github.com/TerminalFi/LSP-copilot/issues/156#issuecomment-2136442438) if you have that file/dir on other signed machine or VSCode, you can copy them.

That worked like a charm, thanks 👍
