### ISSUE TITLE
Error when no avatar

### ISSUE THREAD

**Issue by du-song** [TerminalFi/LSP-copilot#218]
This should be muted as a user without avatar is valid use case I think?

```
[LSP-copilot][ERROR] Failed to fetch avatar for "myusername" because: HTTP Error 404: Not Found
```

**Comment by jfcherng** [comment]
Could you provide a reproduceable test case?

I can see "myusername"'s avatar.
https://github.com/myusername.png?size=64

**Comment by jfcherng** [comment]
Okay. Probably we can use a blank avatar for it.

**Comment by jfcherng** [comment]
`v0.3.3` has been tagged. It should be available within hours.
