### ISSUE TITLE
Cause crash on Windows

### ISSUE THREAD

**Issue by yanecc** [TerminalFi/LSP-copilot#224]
```
OPENSSL_Uplink(00007FFC722FBD40,08):no OPENSSL_Applink
plugin_host-3.8 has exited unexpectedly, some plugin functionality won't be available until Sublime Text has been restarted
```

The latest update is causing a crash on Windows and removing the plugin can fix it.

**Comment by jfcherng** [comment]
Unfortunately, I can't reproduce it and I don't know how to fix it.

**Comment by jfcherng** [comment]
Maybe related since you are from China. https://blog.csdn.net/qq_17328759/article/details/127802435

**Comment by yanecc** [comment]
> Maybe related since you are from China: https://blog.csdn.net/qq_17328759/article/details/127802435 We introduced the `requests` lib in the latest release.

So it is, thanks.
