### ISSUE TITLE
Invalid params: /doc must have required property 'version'

### ISSUE THREAD

**Issue by julien-garand** [TerminalFi/LSP-copilot#77]
Hi,

Copilot is not working anymore. Here is the error I found in log panel :

> LSP-copilot 6: {'code': -32602, 'message': "Invalid params: /doc must have required property 'version'"}

Thanks for all ! Copilot helps me a lot.

**Comment by jfcherng** [comment]
We've reverted the update to v1.8.1 and fallback to v1.8.0. This change should available within hours.

**Comment by TerminalFi** [comment]
Should have a working PR shortly

**Comment by jfcherng** [comment]
Fixed by https://github.com/TerminalFi/LSP-copilot/pull/79
