### ISSUE TITLE
Completion popup only shows first line

### ISSUE THREAD

**Issue by sebastianhelbig** [TerminalFi/LSP-copilot#87]
The completion popup only shows the first line of the suggestion and after accepting also only this line is written.

Instead when using panel completions, the full multi-line suggestion is showing up.

![image](https://user-images.githubusercontent.com/5049311/220703259-dfb07a9d-b68a-4e75-8b64-8c321f56970f.png)

![image](https://user-images.githubusercontent.com/5049311/220703777-7013f891-93d2-44d1-8727-3a003eddd31a.png)

**Comment by TerminalFi** [comment]
My first assumption is that if you hit tab the next suggestion would be the following line and is expected. Get completion and Get Panel Completion are two different requests and like Copilot returns things differently. 

I can try and see if this is the case.

**Comment by TerminalFi** [comment]
Yes, this is working as expected. 

You can open the LSP Log Panel and observe the requests and responses. This behavior is copilot and not the plug-in.  

I’d assume you receive the same results using VSCode

**Comment by sebastianhelbig** [comment]
Ok. Thank you for the explanation!
