### ISSUE TITLE
Keybinding for opening/closing suggestion panel

### ISSUE THREAD

**Issue by dchersey** [TerminalFi/LSP-copilot#88]
Hello, loving this so far ... just thinking it would be helpful to have a keybinding option for opening the full (10 suggestion) panel and then closing it without accepting any of them. 

Essentially keybindings for the hamburger menu in the auto-suggest popup and the close button in the panel that appears when you click that.

**Comment by jfcherng** [comment]
yes, the command name is `copilot_get_panel_completions`

**Comment by TerminalFi** [comment]
And the other command you are looking for is 

`copilot_close_panel_completion`
