### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by CaptFreezer** [TerminalFi/LSP-copilot#94]
We are behind a Proxyserver and can't connect to Copilot.
I really tried everything from env-variables, to overwrite 'agent.js' with hardcoded proxy-settings.
Is there anything we can do, to connect to Copilot over a proxyserver?

**Comment by jfcherng** [comment]
What's the error msg?

**Comment by CaptFreezer** [comment]
i copied this from the LSP Log Panel with all debug-messages turned on:

:: [13:03:01.403] --> LSP-copilot signInInitiate (4): {}
LSP-copilot: ApplicationInsights:CorrelationIdManager [
LSP-copilot:   Error: connect ETIMEDOUT 0.0.12.56:80
LSP-copilot:       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
LSP-copilot:     errno: -110,
LSP-copilot:     code: 'ETIMEDOUT',
LSP-copilot:     syscall: 'connect',
LSP-copilot:     address: '0.0.12.56',
LSP-copilot:     port: 80
LSP-copilot:   }
LSP-copilot: ]
LSP-copilot: ApplicationInsights:CorrelationIdManager [
LSP-copilot:   Error: connect ETIMEDOUT 0.0.12.56:80
LSP-copilot:       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
LSP-copilot:     errno: -110,
LSP-copilot:     code: 'ETIMEDOUT',
LSP-copilot:     syscall: 'connect',
LSP-copilot:     address: '0.0.12.56',
LSP-copilot:     port: 80
LSP-copilot:   }
LSP-copilot: ]
:: [13:05:13.587] <~~ LSP-copilot (4) (duration: 132183ms): {'message': 'Request signInInitiate failed with message: connect ETIMEDOUT 140.82.121.4:443', 'code': -32603}

**Comment by jfcherng** [comment]
After checking server's source codes, it looks like the env variable names are

- http_proxy
- https_proxy

Maybe try to set env like `http_proxy=http://proxy.example.com:3129`?

**Comment by jfcherng** [comment]
Can you try this PR: https://github.com/TerminalFi/LSP-copilot/pull/95 ?

**Comment by rezakr** [comment]
Hi, I was going to raise an issue like this a moment ago but I saw this.

Can you perhaps add support for socks5 as well? I tried setting the env variables for it on both `http_proxy` and `https_proxy` but it doesn't work.

**Comment by CaptFreezer** [comment]
I downloaded the `feat/proxy` branch and copied the files into my Packages-Folder.
Sublime did something and i restarted it afterwards.
After restarting it, i tried it again and it didn't work.
in my user-settings from lsp-copilot i have this env-variable
```
    "env": {
        "http_proxy": "http://HOST:PORT"
    },
```

**Comment by jfcherng** [comment]
> I downloaded the `feat/proxy` branch and copied the files into my Packages-Folder. Sublime did something and i restarted it afterwards. After restarting it, i tried it again and it didn't work. in my user-settings from lsp-copilot i have this env-variable
> 
> ```
>     "env": {
>         "http_proxy": "http://HOST:PORT"
>     },
> ```
> 
> error-message from Log Panel:
> 
> ```
> :: [16:29:04.244] <~~ LSP-copilot (5) (duration: 131506ms): {'message': 'Request signInInitiate failed with message: connect ETIMEDOUT 140.82.121.4:443', 'code': -32603}
> ```

As per PR's description, that's not how it works. Please see https://github.com/TerminalFi/LSP-copilot/pull/95

**Comment by rezakr** [comment]
@jfcherng I understand, but I cannot figure it out my self. Can you point me to a direction on where I should look in for socks5 support? In Copilot.vim server?
