### ISSUE TITLE
Install LSP and LSP-copilot

### ISSUE THREAD

**Issue by Vegetebird** [TerminalFi/LSP-copilot#97]
Using Package Control: Install Package, I can not find LSP and LSP-copilot. 

<img width="662" alt="image" src="https://user-images.githubusercontent.com/35993705/227582231-9444a2cc-1184-44ae-85e9-9b1dca4be3f3.png">

**Comment by jfcherng** [comment]
Since you are from China, my first guess would be your are using a very old Package Control cache.

**Comment by Vegetebird** [comment]
Thanks! I have successfully installed LSP and LSP-copilot, but the code completion style of Copilot in Sublime is different from that of VSCode. Could you please provide a code completion style for Copilot that is similar to that of VSCode?

sublime with copilot:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/35993705/227681009-b081b01b-c6e5-466c-bcc7-cf4564beb369.png">


vscode with copilot:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/35993705/227681051-f6984bcf-6007-49b1-af68-0ad567198c6f.png">

**Comment by TerminalFi** [comment]
> Thanks! I have successfully installed LSP and LSP-copilot, but the code completion style of Copilot in Sublime is different from that of VSCode. Could you please provide a code completion style for Copilot that is similar to that of VSCode?
> 
> 
> 
> sublime with copilot:
> 
> <img width="931" alt="image" src="https://user-images.githubusercontent.com/35993705/227681009-b081b01b-c6e5-466c-bcc7-cf4564beb369.png">
> 
> 
> 
> 
> 
> vscode with copilot:
> 
> <img width="676" alt="image" src="https://user-images.githubusercontent.com/35993705/227681051-f6984bcf-6007-49b1-af68-0ad567198c6f.png">
> 
> 

There is an experimental option in settings to support this. Please read the settings.

**Comment by Vegetebird** [comment]
I do not want to show "accept" and ''reject", and just want to show like copilot in vscode for simplicity.

**Comment by TerminalFi** [comment]
> I do not want to show "accept" and ''reject", and just want to show like copilot in vscode for simplicity. 

Yes, that is why I told you to read the settings.

**Comment by jfcherng** [comment]
lol. Our settings highly rely on LSP-json.

**Comment by Vegetebird** [comment]
Thanks!

<img width="811" alt="image" src="https://user-images.githubusercontent.com/35993705/227701358-da95ee63-6db8-496e-b42b-6c1673f1fd96.png">
